
parameters:
    tex2png.class: Gregwar\Tex2pngBundle\Tex2pngHandler
    tex2png.service: Gregwar\Tex2pngBundle\Services\Tex2pngService

services:
    # Tex2png service
    tex2png:
        class: %tex2png.service%
        arguments: [%gregwar_tex2png.cache_dir%, %tex2png.class%, @service_container]

    # Twig helper
    twig.extension.tex2png:
        class: Gregwar\Tex2pngBundle\Extensions\Tex2pngTwig
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

